### ISSUE TITLE
Change howdy profile from fast to Secure

### ISSUE THREAD

**Issue by shahulhameed8** [boltgolt/howdy#589] opened 2021-09-09 05:02 UTC
Fast – speeds up the scanning process greatly, but it allows more fuzzy matches.
Balanced – relatively quick detection, but might not log you in when further away.
Secure – is the safest option, thought it will take much longer to recognize your face.

certainty Fast is 4.2 
Balance is in between 3.5 to 4.2
Secure is 3.5 like that?

Can you please confirm the above values we correct?

**Comment by boltgolt** [comment] 2021-09-09 06:13
Duplicate of comment on #587. Please do not open duplicates, it will not make me respond faster

**Closed** 2021-09-09 06:13 UTC
Labels: duplicate
