### ISSUE TITLE
Can't add face/use test command

### ISSUE THREAD

**Issue by ChaseFamous** [boltgolt/howdy#78] opened 2018-10-02 17:09 UTC
I've downloaded and installed howdy today and everything seems to have gone well except the fact that I can't add my face. Every time I try to do this (in a well-lit environment or in a dark environment) it tells me that it couldn't detect a face. (No face detected, aborting). When I use the sudo howdy test command I get this: 
sudo howdy test

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

QObject::moveToThread: Current thread (0x8f84cc0) is not the object's thread (0x9115b90).
Cannot move to target thread (0x8f84cc0)

Segmentation fault

I am running Kubuntu (together with Windows 10) on my Lenovo Thinkpad P52.

The howdy version I have is 2.3.1.

**Comment by boltgolt** [comment] 2018-10-02 17:18
Looks like a duplicate of #54

**Closed by boltgolt** 2018-10-02 17:18 UTC
