### ISSUE TITLE
Error adding new model in ArchLinux

### ISSUE THREAD

**Issue by cassioalmeidas** [boltgolt/howdy#402] opened 2020-07-27 16:42 UTC
![Screen Capture_select-area_20200727133937](https://user-images.githubusercontent.com/104586/88568070-c1eee580-d00e-11ea-81ce-0b60e4d81ed0.png)

Linux distribution: ArchLinux

Howdy version: 2.6.0-1

**Comment by boltgolt** [comment] 2020-08-09 09:53
I think this is a duplicate of #375, and although your issue was reported earlier there has been more discussion at #375. Closing this issue to keep the debate in the same place

**Closed by boltgolt** 2020-08-09 09:53 UTC
