### ISSUE TITLE
Fedora 30 config

### ISSUE THREAD

**Issue by msandy1** [boltgolt/howdy#225] opened 2019-06-29 22:02 UTC
I can't seem to get it to run on Fedora 30. I've been able to set the device path. /dev/v4l/by-path/[DEVICE]. but it's still not running for me. every time I test it I get an error saying :

```
[ INFO:0] VIDEOIO: Enabled backends(7, sorted by priority): GSTREAMER(1000); V4L2(990); OPENNI(980); CV_IMAGES(970); CV_MJPEG(960); FIREWIRE(950); UNICAP(940)
OpenCV | GStreamer warning: GStreamer: unable to start pipeline
 (/builddir/build/BUILD/opencv-3.4.4/modules/videoio/src/cap_gstreamer.cpp:872)

(python3:18466): GStreamer-CRITICAL **: 15:46:21.361: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
OpenCV | GStreamer warning: GStreamer: unable to query pipeline state (/builddir/build/BUILD/opencv-3.4.4/modules/videoio/src/cap_gstreamer.cpp:420)
libv4l2: error setting pixformat: Input/output error
VIDEOIO ERROR: libv4l unable to ioctl S_FMT
VIDEOIO ERROR: libv4l unable to ioctl VIDIOCSPICT

CvCapture_OpenNI::CvCapture_OpenNI : Failed to open input file (/dev/v4l/by-path/pci-0000:00:1d.7-usb-0:5:1.2-video-index0): Bad file extension

Opening a window with a test feed

Press ctrl+C in this terminal to quit
Click on the image to enable or disable slow mode

No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted

```

I've tried to reinstall xcb but that made no difference? Is howdy working with fedora 30. Is there a default recommended post install configuration?

**Comment by hamomel** [comment] 2019-07-09 05:21
I managed to make it run on Fedora 30, but it only works with sudo not on login screen. I found that ir-camera on my Thinkpad T580 is on /dev/video0 and set device_path = /dev/video0. Also I use Fedora wits Xorg not Wayland. I have the same warnings from GStreamer, but after these warnings I get "Identified face my_user_name" and log in as su.
Does anyone know how to make it start on login screen?

**Comment by boltgolt** [comment] 2019-09-16 14:26
Sorry, your issue was earlier but to keep the discussion in 1 place i'll mark this as a duplicate of #233

**Closed by boltgolt** 2019-09-16 14:26 UTC
Labels: distro: fedora, duplicate
