### ISSUE TITLE
GStreamer warning with $OPENCV_LOG_LEVEL=ERROR

### ISSUE THREAD

**Issue by fanganpai** [boltgolt/howdy#492] opened 2021-01-08 14:55 UTC
Howdy can works on my system, however, I got warning like:
```Attempting face detection
[ WARN:0] global /build/opencv/src/opencv-4.5.1/modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0] global /build/opencv/src/opencv-4.5.1/modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /build/opencv/src/opencv-4.5.1/modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
````
And exporting OPENCV_LOG_LEVEL=ERROR as an environment variable don't fix it.
my .bashrc like that:
`
OPENCV_LOG_LEVEL=ERROR
`
And:
`
$ sudo echo $OPENCV_LOG_LEVEL

ERROR
`

Linux distribution (if applicable):Manjaro 20.2.1 Nibia with Linux 5.10.5-1

Howdy version (`sudo howdy version`):2.6.1

**Comment by boltgolt** [comment] 2021-01-08 15:09
Duplicate of #318, has potential fix too

**Closed by boltgolt** 2021-01-08 15:09 UTC
