### ISSUE TITLE
activate in login

### ISSUE THREAD

**Issue by viaunix** [boltgolt/howdy#217] opened 2019-05-24 19:32 UTC
_Please describe the issue in as much detail as possible, including any errors and traces_

How do I activate the camera on login?
despite the installation and detection of the images and tests but when you turn on the computer only the option of 'password' in text mode appears.

----

I've searched for similar issues already, and my issue has not been reported yet.

Linux distribution (if applicable):

Howdy version:

**Comment by boltgolt** [comment] 2019-06-09 17:05
Duplicate of #179

**Closed by boltgolt** 2019-06-09 17:05 UTC
Labels: duplicate
