### ISSUE TITLE
BadDrawable /invalid Pixmap or Window parameter/ 9

### ISSUE THREAD

**Issue by amodry** [Boltgolt/howdy#38] opened 2018-05-12 09:26 UTC
Hello,
i have problem with howdy...when i run howdy test, it shows this:
Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x3a00010

Can somebody help with that?

Thanks in advance.

**Comment by Boltgolt** [comment] 2018-05-12 09:28
I think this could be a duplicate of #23, could you try that solution?

**Closed** 2018-05-16 15:55 UTC
Labels: duplicate
