### ISSUE TITLE
Can't login to Kubuntu 21.04 desktop, hangs after entering password.

### ISSUE THREAD

**Issue by rdwhitney** [boltgolt/howdy#547] opened 2021-05-23 14:35 UTC
Had howdy working for about a week with no problems, other than it failing to recognize me about 50% of the time because I only took two pictures of myself in the setup (I think something like a dozen is recommended). But this morning when I went to boot up my machine, after entering my password at the login screen (because it didn't recognize me) and hitting enter, nothing happened. I could still backspace and re-enter my password - I tried a dozen times or so and nothing. So I hit ctl-alt-f2 to go to tty2, and I was able to login fine there (and there the howdy face recognition worked, go figure). But after logging in with tty2, returning to the GUI login screen still prompted me to enter the password, so I was still stuck. When I tried going to ctl-alt-f7, I got a black screen with a blinking white text cursor that never changed.

After googling it, I tried updating all packages from tty2 - didn't help, and then running apt-get install ubuntu-desktop, just in case something had gotten screwed up there - also didn't help (always rebooted after each of these changes). Perplexed, I decided to run apt-get purge howdy, and lo and behold, when I rebooted, I was able to login fine.The only thing that changed with my configuration in the last few days would be regularly running apt-get update, so maybe an update with howdy yesterday broke something?

----

I've searched for similar issues already, and my issue has not been reported yet. (Didn't see anything after about 10 min of searching)

Linux distribution (if applicable): Kubuntu 21.04 (KDE)

Howdy version (`sudo howdy version`): 2.6.1

**Comment by boltgolt** [comment] 2021-05-31 14:55
There have been no updates to Howdy at all this year so that can't be it. I think the issue is with your greeter. I've seen this issue a couple of times now where Howdy works fine in console but not on login for whatever reason. It's out of scope for this project and is caused by an improper PAM implementation within your greeter

**Closed by boltgolt** 2021-05-31 14:55 UTC
Labels: dependency
